### ISSUE TITLE
Use cases for Baggage

### ISSUE THREAD

**Issue by yurishkuro** [w3c/baggage#10]
From https://github.com/w3c/distributed-tracing-wg/blob/master/meeting_notes/2019-04-23.md

> We should make a survey who is actually going to implement it. We have to check if it’s worth being a standard.

I wrote a post listing a number of use cases: https://medium.com/jaegertracing/embracing-context-propagation-7100b9b6029a

**Comment by dyladan** [comment]
Transcribed from the blog post for quick viewing:

- Marking traffic as synthetic
- Attribute shared resource usage (gdocs and gmail share resources, how do you know which business line is making a particular call)
- QoS (some user actions are more important than others)

**Comment by discostu105** [comment]
Adding one use case: An APM agent could use correlation-context entries as additional attributes/annotations for a span or metric that is being recorded.

**Comment by discostu105** [comment]
Based on that, would anyone disagree with the following statement?

 1. Applications and libraries can write to correlation context.
 1. Applications and libraries can read from correlation context and can base their behavior on it's content.
 1. APM agents can read from correlation context, to annotate spans and metrics with it.
 1. APM agents shall *NOT* write to correlation context in order to store any correlation data. This is what TraceContext `tracestate` shall be used for.
