### ISSUE TITLE
revert arbitrary "cookie" rationale

### ISSUE THREAD

**Issue by codefromthecrypt** [w3c/baggage#22]
"*Maximum number of name-value pairs* - this limit was taken as a number of cookies allowed by Chrome."

this seems a very weak rationale as cookies were defined for a different purpose. 180 pairs.. to pass along every hop, seems excessive

**Comment by adriancole** [comment]
considering trace instrumentation have to process and propagate these. much smaller limits are more reasonable, similar to the tracestate header. I'm not sure the rationale for those were fully inventoried, some looked a bit reverse engineered from hunches. I'll give a concrete example.

A number above 32 causes problems for those encoding pairwise as state changes cannot be tracked with a 64bit bitset. Yes, we can use blocked bitsets and other techniques, but some care should be taken to not set limits hugely especially without relevant rationale to do so.

**Comment by yurishkuro** [comment]
32 sgtm

**Comment by dyladan** [comment]
I wonder if @SergeyKanzhelev could provide some stats about how many pairs they commonly see in the wild

**Comment by SergeyKanzhelev** [comment]
@Kanwaldeep can we query number of records in CC used by internal apps? From what I seen it was 3-4 pairs so 32 sounds enough for every single feature. 

With the combination of features I can imagine how it may theoretically be reached. Client App Version, Marketing campaign, FlightID and requests routing information, user and session tracking, etc. Would it be better to limit the overall size instead of the number of pairs?

I also agree that comparison with cookies may not be the best rationale. However it gives big enough number that even theoretically hard to reach and somehow proven to be working for the "similar" functionality. As 32 seems to be an easily reachable (easier than 180), we will hit the problem of describing which entries to kick out of correlation context. In `tracestate` it was enforced via ordering of pairs. Which may not be the best option here.

**Comment by danielkhan** [comment]
As it is up to the producer/consumer what to propagate the spec will remove the limit but will add normative text on how to trim the header (only full key/value pairs).
